Config
datopian/markdowndb pull request #84
Opened 2023-12-05 01:15 UTC by mohamedsalem401

- add configuration file 
- add computed fields
- add npx markdowndb init CLI script that will bootstrap the config file

2023-12-06 15:34 UTC, rufuspollock commented
@mohamedsalem401 does this reflect the comments in the PR yesterday re the definition in the README PR of this feature?

2023-12-06 19:10 UTC, rufuspollock requested changes
I can already see at least one issue is that the system should continue to work *without* a config folder.

In general, i'd strongly recommend (as discussed last week) that we get an example working without the config folder stuff but just with passing config to the relevant class or function e.g. `buildMarkdownDB` or whatever it is called.

once that API is well shaped adding config in a file is relatively straightforward ...

2023-12-06 19:10 UTC, rufuspollock commented on src/bin/index.js
> +import { promises as fs } from 'fs';
fs is defined but not used.

2023-12-06 19:10 UTC, rufuspollock commented on src/bin/index.js
> +const [contentPath, configFilePath] = process.argv.slice(2);
What happens if you don't have a config file - this stuff should work with defaults ...

2023-12-06 19:32 UTC, rufuspollock commented
@mohamedsalem401 another general comment - i'd have kept the include/exclude feature for a separate PR. It makes the review easier and faster ...

2023-12-11 18:07 UTC, mohamedsalem401 commented
I will close this for now

2023-12-11 18:07 UTC, closed without merging